name: weathersasa

on:
  push:
    branches:
      - master

jobs:
  deploy-to-digital-ocean-droplet:
    runs-on: ubuntu-latest
    name: deploy weathersasa
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Pull from GitHub and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: cd projects/weathersasa/ && git pull && npm install && npm run build && npm run deploy